// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puntiro.Modules.Identity.Persistence;

#nullable disable

namespace Puntiro.Modules.Identity.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("202608080002_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.AdminSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<Guid>("ActiveOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_organization_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("IdleExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_version");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("SecondFactorVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("second_factor_verified_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("verifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_sessions_public_id");

                    b.HasIndex("IdleExpiresAtUtc", "AbsoluteExpiresAtUtc")
                        .HasDatabaseName("ix_sessions_expiry");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_sessions_user_revoked_at");

                    b.ToTable("sessions", "identity");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("display_email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid?>("ProvisioningOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioning_organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_normalized_email");

                    b.HasIndex("ProvisioningOrganizationId")
                        .HasDatabaseName("ix_admin_users_provisioning_organization_id");

                    b.ToTable("admin_users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_admin_users_status", "status IN ('provisioning', 'active', 'suspended')");
                        });
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.IdentitySecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_security_events");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_security_events_user_occurred_at");

                    b.ToTable("security_events", "identity");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("algorithm");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer")
                        .HasColumnName("iterations");

                    b.Property<DateTimeOffset?>("LastRehashedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rehashed_at");

                    b.Property<int>("MemoryKiB")
                        .HasColumnType("integer")
                        .HasColumnName("memory_kib");

                    b.Property<int>("Parallelism")
                        .HasColumnType("integer")
                        .HasColumnName("parallelism");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<DateTimeOffset>("SetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId")
                        .HasName("pk_password_credentials");

                    b.ToTable("password_credentials", "identity");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.RecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_version");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("verifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recovery_codes");

                    b.HasIndex("UserId", "BatchId")
                        .HasDatabaseName("ix_recovery_codes_user_batch");

                    b.HasIndex("UserId", "UsedAtUtc")
                        .HasDatabaseName("ix_recovery_codes_user_used_at");

                    b.ToTable("recovery_codes", "identity");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.TotpCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<long?>("LastAcceptedCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("last_accepted_counter");

                    b.Property<byte[]>("ProtectedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("protected_secret");

                    b.Property<DateTimeOffset>("ReplacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId")
                        .HasName("pk_totp_credentials");

                    b.ToTable("totp_credentials", "identity");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.AdminSession", b =>
                {
                    b.HasOne("Puntiro.Modules.Identity.Domain.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_admin_users_user_id");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.PasswordCredential", b =>
                {
                    b.HasOne("Puntiro.Modules.Identity.Domain.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_credentials_admin_users_user_id");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.RecoveryCode", b =>
                {
                    b.HasOne("Puntiro.Modules.Identity.Domain.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_codes_admin_users_user_id");
                });

            modelBuilder.Entity("Puntiro.Modules.Identity.Domain.TotpCredential", b =>
                {
                    b.HasOne("Puntiro.Modules.Identity.Domain.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_totp_credentials_admin_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
