// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puntiro.Modules.Integrations.Persistence;

#nullable disable

namespace Puntiro.Modules.Integrations.Persistence.Migrations
{
    [DbContext(typeof(IntegrationsDbContext))]
    [Migration("202608080003_InitialIntegrations")]
    partial class InitialIntegrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integrations")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puntiro.Modules.Integrations.Domain.IntegrationSecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_security_events");

                    b.HasIndex("TokenId");

                    b.HasIndex("OrganizationId", "OccurredAtUtc")
                        .HasDatabaseName("ix_security_events_organization_occurred_at");

                    b.ToTable("security_events", "integrations");
                });

            modelBuilder.Entity("Puntiro.Modules.Integrations.Domain.IntegrationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("ActiveSlot")
                        .HasColumnType("smallint")
                        .HasColumnName("active_slot");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key_version");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("character varying(22)")
                        .HasColumnName("public_id");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<byte[]>("SecretVerifier")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_verifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_tokens");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_tokens_public_id");

                    b.HasIndex("OrganizationId", "ActiveSlot")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_tokens_organization_active_slot")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("OrganizationId", "RevokedAtUtc")
                        .HasDatabaseName("ix_integration_tokens_organization_revoked_at");

                    b.ToTable("integration_tokens", "integrations", t =>
                        {
                            t.HasCheckConstraint("ck_integration_tokens_active_slot", "(revoked_at IS NULL AND active_slot IN (1, 2)) OR (revoked_at IS NOT NULL AND active_slot IS NULL)");

                            t.HasCheckConstraint("ck_integration_tokens_last_used_time", "last_used_at IS NULL OR last_used_at >= created_at");

                            t.HasCheckConstraint("ck_integration_tokens_positive_version", "version > 0");

                            t.HasCheckConstraint("ck_integration_tokens_revoke_metadata", "(revoked_at IS NULL AND revoked_by_user_id IS NULL AND revoke_reason IS NULL) OR (revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL AND revoke_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_integration_tokens_revoked_time", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_integration_tokens_verifier_length", "octet_length(secret_verifier) = 32");
                        });
                });

            modelBuilder.Entity("Puntiro.Modules.Integrations.Domain.IntegrationTokenScope", b =>
                {
                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.HasKey("TokenId", "Scope")
                        .HasName("pk_integration_token_scopes");

                    b.ToTable("integration_token_scopes", "integrations", t =>
                        {
                            t.HasCheckConstraint("ck_integration_token_scopes_scope", "scope IN ('shipments.read', 'shipments.write')");
                        });
                });

            modelBuilder.Entity("Puntiro.Modules.Integrations.Domain.IntegrationSecurityEvent", b =>
                {
                    b.HasOne("Puntiro.Modules.Integrations.Domain.IntegrationToken", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_events_integration_tokens_token_id");
                });

            modelBuilder.Entity("Puntiro.Modules.Integrations.Domain.IntegrationTokenScope", b =>
                {
                    b.HasOne("Puntiro.Modules.Integrations.Domain.IntegrationToken", null)
                        .WithMany("Scopes")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_token_scopes_tokens_token_id");
                });

            modelBuilder.Entity("Puntiro.Modules.Integrations.Domain.IntegrationToken", b =>
                {
                    b.Navigation("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
